ui: tape
browsers:
  - name: chrome
    version: 45..dev

  - name: firefox
    version: 45..beta

  - name: ie
    version: 8..latest

  - name: microsoftedge
    version: 13..latest

  - name: opera
    version: 12..latest

  - name: safari
    version: 9..latest

  - name: android
    version: '4.3..latest'

  - name: iphone
    version: '8.0..latest'

  - name: ipad
    version: '8.0..latest'
